version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - echo "Building the project..."
      - npm run build
  build:
    commands:
      - echo "Deploying to AWS..."
      - serverless deploy --stage $STAGE
  post_build:
    commands:
      - echo "Deployment complete."
artifacts:
  files:
    - '**/*'

